# Generated by Django 5.0 on 2025-01-20 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinteraction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="userinteraction",
            name="recipes_use_user_id_f79887_idx",
        ),
        migrations.AlterField(
            model_name="userinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[("view", "Viewed"), ("save", "Saved"), ("share", "Shared")],
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinteraction",
            unique_together={("user", "recipe", "interaction_type")},
        ),
    ]
