# Generated by Django 5.0 on 2025-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_userinteraction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(help_text="Enter each ingredient on a new line"),
        ),
    ]
