# Generated by Django 5.0 on 2025-01-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_review_unique_together_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="calories_per_serving",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="dietary_preferences",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("gluten_free", "Gluten Free"),
                    ("dairy_free", "Dairy Free"),
                    ("keto", "Keto"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(
                default=15, help_text="Preparation time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_time",
            field=models.IntegerField(
                blank=True, help_text="Total time in minutes", null=True
            ),
        ),
    ]
