# Generated by Django 5.0 on 2025-01-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_favorite_recipe_favorited_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="total_time",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="dietary_preferences",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("gluten_free", "Gluten Free"),
                    ("dairy_free", "Dairy Free"),
                    ("keto", "Keto"),
                    ("none", "None"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(),
        ),
    ]
