# Generated by Django 5.0 on 2025-01-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_remove_recipe_created_by_remove_recipe_total_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="favorited_by",
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_time",
            field=models.IntegerField(
                blank=True, help_text="Total time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(help_text="Cooking time in minutes"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="dietary_preferences",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("gluten_free", "Gluten Free"),
                    ("dairy_free", "Dairy Free"),
                    ("keto", "Keto"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_images/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(help_text="Enter each ingredient on a new line"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="prep_time",
            field=models.IntegerField(
                default=15, help_text="Preparation time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.IntegerField(default=4),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
